spring.application.name=NexusShip

spring.datasource.url=jdbc:postgresql://localhost:5432/Logistics
spring.datasource.username=postgres
spring.datasource.password=postgres




#Show JPA/Hibernate logging messags
#log Sql statements
logging.level.ort.hibernate.SQL=trace
#log values for sql statements
logging.level.ort.hibernate.orm.jdbc.bind=trace